apiVersion: v1
kind: PersistentVolume
metadata:
  name: defjef-data-pv1
  labels:
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /data/various/defjef-data-pv1
