# make sure that the data pathe is accessible on the server
apiVersion: v1
kind: PersistentVolume
metadata:
  name: defjef-data-pv1
  labels:
    type: local
spec:
  storageClassName: local
  persistentVolumeReclaimPolicy: Retain  
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/various/defjef-data-pv1
